let productList = [
  {
    id: 1,
    name: "pepsi",
    type: "drinks",
    description: "get a drink that quenches the thirst",
    status: "approved",
    date_created: "02-03-2017",
  },
  {
    id: 2,
    name: "Coke",
    type: "drinks",
    description: "just one taste",
    status: "pending",
    date_created: "02-03-2017",
  },
  {
    id: 3,
    name: "samsung f2",
    type: "gadget",
    description: "e ready to be everywhere",
    status: "unapproved",
    date_created: "02-05-2017",
  },
  {
    id: 4,
    name: "Iphone",
    type: "Gadget",
    description: "lorem dgh aues hdghfh aadnh",
    status: "approved",
    date_created: "02-03-2017",
  },
  {
    id: 5,
    name: "Rechargeable Fan",
    type: "Gadget",
    description: "Life is good",
    status: "approved",
    date_created: "02-03-2017",
  },
  {
    id: 6,
    name: "Tv set",
    type: "drinks",
    description: "Life is good",
    status: "unapproved",
    date_created: "02-03-2017",
  },
  {
    id: 7,
    name: "pepsi",
    type: "drinks",
    description: "get a drink that quenches the thirst",
    status: "approved",
    date_created: "02-03-2017",
  },
  {
    id: 8,
    name: "Power Bank",
    type: "Gadget",
    description: "teh hefjd 0sk get a drink that quenches the thirst",
    status: "unapproved",
    date_created: "02-03-2017",
  },
  {
    id: 9,
    name: "T-shirt",
    type: "Clothing",
    description: "get yourself cover and slay ",
    status: "pending",
    date_created: "05-03-2017",
  },
  {
    id: 10,
    name: "Hair comb",
    type: "drinks",
    description: "Slay and gray",
    status: "unapproved",
    date_created: "02-03-2017",
  },
];


export default productList